services:
  - type: web
    name: fitness-tracker-client
    env: node
    buildCommand: |
      cd client
      npm install
      npm run build
    startCommand: |
      cd client
      npm run serve
    envVars:
      - key: NODE_ENV
        value: production
    plan: free

  - type: web
    name: fitness-tracker-server
    env: node
    buildCommand: |
      cd server
      npm install
    startCommand: |
      node server.js
    envVars:
      - key: NODE_ENV
        value: production
    plan: free
    healthCheckPath: "/health"