services:
  - type: web
    name: final-fitness-tracker-app
    env: node
    rootDir: server
    buildCommand: cd ../client && npm install && npm run build && cd ../server && npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 10000  # or just let Render set this automatically